fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
      address: "example@example.com"
      sender_name: "Sender Name"
#  registration:
#      form:
#          type: FOS\UserBundle\Form\Type\RegistrationFormType
#          name: fos_user_registration_form
#          validation_groups:  [RegistrationValidation]